### ISSUE TITLE
Page is ignored when adding fields

### ISSUE THREAD

**Issue by ofcaah** [MatthiasValvekens/pyHanko#9] opened 2021-03-12 07:45 UTC
**Describe the bug**
There seems to be a regression between 0.3.0 and 0.4.0 -- version 0.4.0 insists on adding empty signature fields on page 1 of the document, while version 0.3.0 honors command line arguments. Didn't see this fixed when looking through commits, however I did not test current version from git.

**Comment by MatthiasValvekens** [comment] 2021-03-12 17:02
Huh, that's strange. Guess that's what I get for running all my tests on single-page PDFs. I'll look into it, thanks for reporting! :+1:

**Comment by MatthiasValvekens** [comment] 2021-03-12 23:14
Hmm, I can't reproduce this against the current master. Signing a two-page file with `--field '2/10,10,50,30/Sig1'` puts the signature on the second page on my end, and the `addfields` command also seems to work as advertised.

I recently refactored the form field initialisation code though, which might have inadvertently fixed the issue you're seeing. I added a regression test for good measure (see 45816032b480d55aedc9c6bf39cff1b3016ae0b7).

I'll close this for now, but feel free to reopen it if you run into the same problem later (or if I misunderstood what you're asking).

**Closed by MatthiasValvekens** 2021-03-12 23:14 UTC
Labels: bug
